apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: echo
  namespace: cnpe-istio-canary
spec:
  host: echo-stable
  subsets:
  - name: stable
    labels:
      app: echo
  - name: canary
    labels:
      app: echo
