apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: backend-fault
  namespace: cnpe-fault
spec:
  hosts:
  - backend
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 50
    route:
    - destination:
        host: backend
